# Generated by Django 4.1.7 on 2023-07-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_id_verification_alter_profile_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
