# Generated by Django 4.1.7 on 2023-07-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_is_verified_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_verification',
            field=models.ImageField(upload_to='id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.ImageField(default='default.jpg', upload_to='passports'),
        ),
    ]
