# Generated by Django 4.1.7 on 2023-08-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_id_verification_alter_profile_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
