# Generated by Django 4.1.7 on 2023-08-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='designation',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('RIDER', 'RIDER')], max_length=50, null=True),
        ),
    ]
