# Generated by Django 4.1.7 on 2023-08-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_image',
            field=models.ImageField(default='default.jpg', upload_to='stocks_images'),
        ),
    ]
