# Generated by Django 4.1.7 on 2023-08-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_type_alter_stock_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_item_size',
            field=models.IntegerField(null=True),
        ),
    ]
