# Generated by Django 4.1.7 on 2023-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_payment_id_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ussd', 'ussd'), ('bank-card', 'bank-card'), ('bank-transfer', 'bank-transfer')], max_length=50, null=True),
        ),
    ]
