# Generated by Django 4.1.7 on 2023-09-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_plan',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('6-month', '6-month'), ('Yearly', 'Yearly')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
