# Generated by Django 4.1.7 on 2023-08-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_size',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='order_complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_complete_image', models.ImageField(upload_to='order_complete')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
