# Generated by Django 4.1.7 on 2023-08-16 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_order_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_la',
            field=models.CharField(choices=[('agege', 'Agege'), ('ajeromi-ifelodun', 'Ajeromi-Ifelodun'), ('alimosho', 'Alimosho'), ('amuwo-odofin', 'Amuwo-Odofin'), ('apapa', 'Apapa'), ('badagry', 'Badagry'), ('epe', 'Epe'), ('Eti-Osa', 'Eti-Osa'), ('ibeju-lekki', 'Ibeju-Lekki'), ('ifako-ijaiye', 'Ifako-Ijaiye'), ('ikeja', 'Ikeja'), ('ikorodu', 'Ikorodu'), ('kosofe', 'Kosofe'), ('lagos-island', 'Lagos Island'), ('lagos-mainland', 'Lagos Mainland'), ('mushin', 'Mushin'), ('ojo', 'Ojo'), ('oshodi-isolo', 'Oshodi-Isolo'), ('somolu', 'Somolu'), ('surulere', 'Surulere')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
