# Generated by Django 4.1.7 on 2023-08-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_order_la_alter_order_rider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='uncomplete', max_length=50),
        ),
    ]
